### ISSUE TITLE
Import module not displayed

### ISSUE THREAD

**Issue by gslongo** [unamur-dev/odoo-account#3]
Hi,

We can't see the link of the module to import CODA file. There is no how to. Any access right to grant ? Could you please explain how to import CODA file ?

Maybe it requires Odoo Entrerprise ?

NB: Odoo 9

Thanks !

**Comment by fdegrave** [comment]
Hi,

In fact it works exactly like the "enterprise" CODA module. So the official documentation should solve your problem: https://www.odoo.com/documentation/user/9.0/fr/accounting/bank/feeds/coda.html (in french) or https://www.odoo.com/documentation/user/9.0/nl/accounting/bank/feeds/coda.html (in dutch).

Cheers,

François

**Comment by gslongo** [comment]
OK thanks for answer.

Not sure if I need Odoo enterprise to use this module? Because I have no "Import Statement" link in the menu. We are new in Odoo and are just deploying the tool for the next year :-)

Thanks !

**Comment by fdegrave** [comment]
No need for Odoo enterprise, we don't have it either and I wouldn't have created this AGPL module otherwise :-)

Once the module is installed, you just need to set up your bank journal(s) to allow importing statements (field 'Bank feeds' set to 'File import').
