### ISSUE TITLE
Missing about info

### ISSUE THREAD

**Issue by danger89** [unamur-dev/odoo-account#8]
So, what can we do with 'account_report_template'? There is no readme.md which listing the features.
Or something..

Can you explain me how and why should I use this add-on? Maybe you can add this info to a README.md as well.

Regards,
Melroy

**Comment by fdegrave** [comment]
Hi,

I haven't had time to work on this recently. However you are right, I should add a README file. In the meantime you can read in  __manifest__.py: 
"This is a module doing the same things as the official Odoo module for accounting reports, but the inner working is completely different (the authors have never seen the code of the closed-source module).
It depends on the generic table_report module (https://github.com/unamur-dev/odoo-tools)."

For the moment only the Belgian VAT declaration report uses this template engine.

Cheers,

François

**Comment by danger89** [comment]
Hi thanks for your fast reply.

I'm from The Netherlands, is it hard to use it for the Dutch VAT as well?
I'm using:
https://github.com/odoo/odoo/blob/10.0/addons/l10n_nl/data/account_tax_template.xml

**Comment by fdegrave** [comment]
I'm not familiar at all with the Dutch VAT declarations, sorry I can't answer that...
